---
# This is a template for your client configuration.
#
# Follow these steps to get this sample application running:
#
# 1. Make a copy of this file and name it `client_config.yml`.
#
# 2. Go to the Sage Developer Self Service at
#    https://developerselfservice.sageone.com/ and sign up/sign in.
#
# 3. Create a new application (app) and copy the values for Client ID and
#    Client Secret into the fields below.
#
# 4. Depending on the way you run the sample app (Docker environment,
#    local Apache, etc.) adjust the hostname/port of the callback URL
#    below. Add the same callback URL to your client application in the
#    Sage Developer Self Service.

config:
  client_id: "476d4ab74224c429038a"
  client_secret: "af547fa48d082868c299b20cdfe94899a6686e20"
  callback_url: "https://www.softonline.com.br/gardenflora/sage/"
...

#config:
#  client_id: "6eefa97b-c4f1-466c-a46c-157940960e7c/a9128a95-f8ff-473f-baa9-83513966d822"
#  client_secret: "X)*SN~BS-cwOIBRg)J93"
#  callback_url: "https://www.softonline.com.br/gardenflora/sage/"
#...

